### ISSUE TITLE
Register map mistake

### ISSUE THREAD

**Issue by EmbeddedMan** [sparkfun/Qwiic_Twist#4]
From the SparkFun product page, there is a "register map" (for some reason simply a graphic image, making it super-tiny and hard to read on my high res screen) here : https://cdn.sparkfun.com/r/600-600/assets/5/3/d/5/6/RegisterMap.jpg

It shows that register 5 is the encoderCount_MSB and 6 is the encoderCount_LSB. However, in version 1.0 of the firmware, it appears that these bytes are backwards. I had to treat register 6 as the MSB and 5 as the LSB for my code to work properly.

I haven't tested any of the other 16-bit register values, but they should be checked as well to make sure they're in the right order, and the 'register map' should be updated. Also, how about that register mab be an HTML table rather than a JEPG? Even a PDF would be zoomable.

**Comment by nseidle** [comment]
Thanks EmbeddedMan! Register map is available both JPG and [PDF](https://cdn.sparkfun.com/assets/learn_tutorials/8/4/6/Qwiic_Twist_Register_Map_-_Fixed_Endianness.pdf) (now updated with LE) on [the hookup guide](https://learn.sparkfun.com/tutorials/qwiic-twist-hookup-guide#register-map). I added PDF and fixed JPG size on product page as well.

Looks like my [GCC structs](https://github.com/sparkfun/Qwiic_Twist/blob/master/Firmware/Qwiic_Twist/Qwiic_Twist.ino#L82) are LE by default (oh the [endianness fights](https://news.ycombinator.com/item?id=16187939)!). Sorry for the confusion. I'll update the map, images, and PDFs.

Note: The firmware version register is still BE.
