### ISSUE TITLE
Schematic has wrong I2C address listed

### ISSUE THREAD

**Issue by EmbeddedMan** [sparkfun/Qwiic_Twist#5]
The current version of the Eagle Schematic for this product lists it's I2C address as 0x5B (default). However, it does not respond to 0x5B out of the box.

Instead, if you look at the 'register map' here : https://cdn.sparkfun.com/r/600-600/assets/5/3/d/5/6/RegisterMap.jpg (linked to from the SparkFun product page for this product) it says the I2C address is 0x3F, which the board does respond to out of the box. (And the line in the firmware const byte I2C_ADDRESS_DEFAULT = 0x3F; also reflects this address.)

Either the schematic should be updated to reflect the firmware and register map, or the register map and firmware should be updated to reflect the schematic.

**Comment by nseidle** [comment]
Sorry! My fault. Schematic text was pulled in from previous product. SCH on repo has been fixed. PDF on product page has been fixed.

Default I2C is 0x3F. With I2C command the address can be set to any legal address. Closing jumper forces address to 0x3E regardless of what user may have set it to via software.
